openapi: 3.0.3
info:
  title: ReversePrint_prod openAPI спецификация
  description: Title
  version: 1.0.0
servers:
  - url: 'https'

paths:
  /api/product:
    post:
      summary: Манипуляции с инстансом продукта
      tags:
        - Product
      requestBody:
        description: Первичное создание инстанса продукта, продукт состоит из блоков цвета, размера, продукта
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInstanceCreateObject'
      responses:
        200:
          description: json представление созданного объекта
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductInstanceCreatedObject'


components:
  schemas:
    ProductInstanceCreateObject:
      type: object
      properties:
        color:
          $ref: '#/components/schemas/ColorObject'
        size:
          $ref: '#/components/schemas/SizeObject'
        product:
          $ref: '#/components/schemas/ProductObject'
        article:
          type: string
          minLength: 9
          maxLength: 9
        stockBalance:
          type: number
          minimum: 0

    ProductInstanceCreatedObject:
      allOf:
        - $ref: '#/components/schemas/ProductInstanceCreateObject'
        - type: object
          properties:
            id:
              type: number
            created_at:
              type: integer
            updated_at:
              type: integer


    ColorObject:
      type: object
      properties:
        name:
          type: string
          uniqueItems: true
        value:
          type: string

    SizeObject:
      type: object
      properties:
        value:
          type: string
          uniqueItems: true

    ProductObject:
      type: object
      properties:
        name:
          type: string
          uniqueItems: true
        description:
          type: string
          maxLength: 500
        price:
          type: number
          minimum: 0
        sex:
          type: string
          enum:
            - uni
            - male
            - female

